name: Update Client

on:
  workflow_dispatch

jobs:
  push-to-registry:
    name: Push Image to Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          repository: keyready/sequoialab-test
          token: ${{ secrets.GH_PASS }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: keyready/sequoialab-test

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-client:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs:
      - push-to-registry
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build client
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          push: false
          script: |
            sudo apt-get update
            sudo apt-get install -y docker.io
            
            docker pull keyready/sequoialab-test:master
            docker run -d --name client_container keyready/sequoialab-test:master
            docker cp client_container:/.svelte-kit/output/. /usr/client-static/
            docker stop client_container
            docker rm client_container


  nginx-restart:
    name: Restart Nginx
    needs: build-client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Nginx restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sudo systemctl restart nginx